In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ml-model-deployment/main/storepurchasedata_large.csv')


In [3]:
dataset.head()

Age  Salary  Purchased
0   18   20000          0
1   19   22000          0
2   20   24000          0
3   21   28000          0
4   22   60000          1

In [4]:
dataset.describe()

Age        Salary    Purchased
count  1554.000000   1554.000000  1554.000000
mean     44.296010  57042.471042     0.694981
std      17.462458  21209.244800     0.460564
min      18.000000  20000.000000     0.000000
25%      27.000000  46000.000000     0.000000
50%      43.000000  60000.000000     1.000000
75%      62.000000  66000.000000     1.000000
max      69.000000  96000.000000     1.000000

In [5]:

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [7]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(10, activation='relu'),
  tf.keras.layers.Dense(2, activation='softmax')
])

In [9]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [10]:
model.fit(X_train, y_train, epochs=50)


Epoch 1/50
39/39 [==============================] - 1s 2ms/step - loss: 0.6521 - accuracy: 0.6372
Epoch 2/50
39/39 [==============================] - 0s 2ms/step - loss: 0.4575 - accuracy: 0.9171
Epoch 3/50
39/39 [==============================] - 0s 2ms/step - loss: 0.3250 - accuracy: 0.9622
Epoch 4/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2572 - accuracy: 0.9517
Epoch 5/50
39/39 [==============================] - 0s 2ms/step - loss: 0.2140 - accuracy: 0.9517
Epoch 6/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1833 - accuracy: 0.9533
Epoch 7/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1622 - accuracy: 0.9525
Epoch 8/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1493 - accuracy: 0.9541
Epoch 9/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1398 - accuracy: 0.9525
Epoch 10/50
39/39 [==============================] - 0s 2ms/step - loss: 0.1338 - accuracy: 0.9541
Epoch 11/50
39/39 [

In [11]:
loss, accuracy =model.evaluate(X_test, y_test)


10/10 [==============================] - 0s 3ms/step - loss: 0.1117 - accuracy: 0.9550


In [12]:
loss

0.11171001195907593

In [13]:
accuracy

0.9549839496612549

In [14]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 2)                 22        
                                                                 
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [15]:
 prediction1 = model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction1

array([0.638857], dtype=float32)

In [16]:
predict2 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict2

array([0.00790193], dtype=float32)

In [17]:
model.save('customer_behavior_model/1')


INFO:tensorflow:Assets written to: customer_behavior_model/1\assets


In [18]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [19]:
!ls customer_behavior_model/1

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [20]:
from tensorflow.keras.models import load_model


In [21]:
cust_model = load_model('customer_behavior_model/1/')

In [22]:
 prediction3 = cust_model.predict(sc.transform(np.array([[42,50000]])))[:,1]
 prediction3

array([0.638857], dtype=float32)

In [23]:
predict4 = model.predict(sc.transform(np.array([[20,40000]])))[:,1]
predict4

array([0.00790193], dtype=float32)

In [24]:
sc.transform(np.array([[20,40000]]))

array([[-1.40863043, -0.81755432]])

In [25]:
sc.transform(np.array([[42,50000]]))

array([[-0.15065689, -0.34524533]])

In [26]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [27]:
!zip -r customermodel.zip customer_behavior_model  

'zip' is not recognized as an internal or external command,
operable program or batch file.


In [28]:
!ls


'ls' is not recognized as an internal or external command,
operable program or batch file.


In [29]:
from google.colab import files


ModuleNotFoundError: No module named 'google.colab'

In [ ]:
!pip install tensorflowjs

In [ ]:
import tensorflowjs as tfjs


In [ ]:
tfjs.converters.save_keras_model(model, "/content/")

/usr/local/lib/python3.6/dist-packages/tensorflowjs/converters/keras_h5_conversion.py:123: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  return h5py.File(h5file)


In [ ]:
!ls

customer_behavior_model  group1-shard1of1.bin  sample_data
customermodel.zip	 model.json


In [ ]:
!cat model.json

{"format": "layers-model", "generatedBy": "keras v2.4.0", "convertedBy": "TensorFlow.js Converter v2.7.0", "modelTopology": {"keras_version": "2.4.0", "backend": "tensorflow", "model_config": {"class_name": "Sequential", "config": {"name": "sequential", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 2], "dtype": "float32", "sparse": false, "ragged": false, "name": "dense_input"}}, {"class_name": "Dense", "config": {"name": "dense", "trainable": true, "dtype": "float32", "units": 10, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_1", "trainable": true, "dtype": "float32", "units": 10, "activation": "relu", "use_bias": true, "kernel_initiali

In [ ]:
from google.colab import files


In [ ]:
files.download('model.json')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
!ls

customer_behavior_model  group1-shard1of1.bin  sample_data
customermodel.zip	 model.json


In [ ]:
files.download('group1-shard1of1.bin')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>